# Generated by Django 3.1.6 on 2021-02-13 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('somking', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('selfmeter', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('polythank', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('lanlord', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('parking', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('pets', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('closedtoroad', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
                ('condition', models.CharField(choices=[('U', 'Used'), ('S', 'Semi Used')], max_length=50)),
                ('propertytype', models.CharField(choices=[('H', 'House'), ('F', 'Flat'), ('A', 'Apartment'), ('D', 'Duplex'), ('O', 'Others')], max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('bathromms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor')),
            ],
        ),
    ]
