# Generated by Django 3.1.6 on 2021-02-13 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('decription', models.TextField(max_length=300)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
